#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

source "$HOME/.config/sketchybar/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  position=top
  height=25
  blur_radius=10
  color=$TRANSPARENT
  corner_radius=10
  y_offset=5
  margin=15
  padding_left=0
  padding_right=0
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:14.0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=$MAIN_COLOR
  label.color=$MAIN_COLOR
  background.color=$ITEM_BG_COLOR
  background.corner_radius=7
  background.height=23
  icon.padding_left=4
  icon.padding_right=5
  label.padding_left=5
  label.padding_right=4
)
sketchybar --default "${default[@]}"

# # -- Left Side Items --
source $ITEM_DIR/apple.sh
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Center Items --
# source $ITEM_DIR/spotify.sh
source $ITEM_DIR/aerospace_mode.sh

# # -- Right Side Items --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update